name: ERL_Ubuntu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python基础
  - python=3.6
  - pip
  
  # 科学计算核心包
  - numpy=1.19.2
  - scipy=1.5.2
  - matplotlib=3.2.2
  - pandas=1.1.5
  - seaborn=0.9.0
  
  # 机器学习框架
  - tensorflow=1.15.0
  - pytorch=1.8.1
  - torchvision=0.9.1
  
  # 强化学习环境
  - gym=0.21.0
  
  # 其他必要包
  - h5py=2.10.0
  - pillow=8.4.0
  - pyyaml=6.0
  - tqdm=4.64.1
  - joblib=1.1.1
  - psutil=5.9.4
  - cloudpickle=2.2.0
  
  # 可视化和监控
  - tensorboard=1.15.0
  - wandb=0.13.10
  
  # 开发工具
  - cython=0.29.24
  
  # pip安装的包
  - pip:
    - mujoco-py==2.1.2.14
    - box2d==2.3.10
    - pyglet==1.5.27
    - autograd==1.6.2
    - cma==2.7.0
    - fastrand==1.7.0
    - gtimer==1.0.0b5
    - imageio==2.15.0
    - opt-einsum==3.3.0
    - protobuf==3.19.6
    - scikit-learn==0.24.2
    - setproctitle==1.2.3
    - threadpoolctl==3.1.0
    - urllib3==1.26.14
    - gymnasium==0.26.3
    - gymnasium-notices==0.0.1